---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0  # Use the ref you want to point at
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-case-conflict
          - id: check-json
          - id: pretty-format-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-xml
          - id: requirements-txt-fixer
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.11
      hooks:
        # Run the linter.
        #   - id: ruff
        #     types_or: [python, pyi, jupyter]
        #     args: [--fix]
        #     exclude: |
        #         (?x)^(
        #             .*[Tt]est.*|
        #             .*__init__.py
        #         )$
        # Run the formatter.
          - id: ruff-format
            types_or: [python, pyi, jupyter]
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v20.1.5  # Use the sha / tag you want to point at
      hooks:
          - id: clang-format
            files: |
                (?x)^(
                    .*\.txx|
                    .*\.hxx|
                    .*\.cxx
                )$
            types_or: [text]
    - repo: https://github.com/scop/pre-commit-shfmt
      rev: v3.11.0-1
      hooks:
          # Choose one of:
          - id: shfmt  # prebuilt upstream executable
            args: [--indent=4, -w, -s]
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
            args: [--severity=warning]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.37.1  # or higher tag
      hooks:
          - id: yamllint
            args: [--strict, '--config-data={extends: relaxed, rules: {line-length: {max: 120}}}']
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3  # or other specific tag
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0  # Use the ref you want to point at
      hooks:
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
